services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor-Droplet-Stage
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - redis
    networks:
      - monitoring-stack
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis-Droplet-stage
#    ports:
#      - 6379:6379
    networks:
      - monitoring-stack
    restart: unless-stopped

networks:
  monitoring-stack:
    driver: bridge
    name: cadvisor-bridge  # Explicitly set the network name
