services:
  prometheus:
    image: prom/prometheus:v3.3.0
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prom-data:/prometheus
    # user: "nobody:nobody"  # Add this line
    extra_hosts:
      - host.machine:host-gateway
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  blackbox_exporter:
    image: prom/blackbox-exporter:v0.26.0
    container_name: blackbox_exporter
    ports:
      - 9115:9115
    restart: unless-stopped
    volumes:
      - ./blackbox.yml:/etc/blackbox_exporter/config.yml
    depends_on:
      - prometheus
    extra_hosts:
      - host.machine:host-gateway
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:9115/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  grafana:
    image: grafana/grafana:11.6.0
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SERVER_DOMAIN=b93f0a5b4d48.sn.mynetname.net
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=123456
    volumes:
      - ./grafana-data:/var/lib/grafana
    extra_hosts:
      - host.machine:host-gateway
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000/login"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
