global:
  scrape_interval: 60s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          - localhost:9090

  - job_name: vms-node-exporter
    scrape_interval: 30s
    scrape_timeout: 2s
    honor_labels: true
    static_configs:
    - labels:
        hostname: PC
      targets:
      - 10.10.10.249:9100
    - labels:
        hostname: Raspberry-PI-5
      targets:
      - 10.10.10.251:9100

  - job_name: 'blackbox-exporter-icmp'
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
       - targets:
         - 8.8.8.8
         - 4.2.2.4
         - 1.1.1.1
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115

          #______Blackbox DNS________________##
  - job_name: 'blackbox-exporter-dns'
    metrics_path: /probe
    params:
      module: [dns_probe]
    static_configs:
      - targets:
        - "8.8.8.8"
        - "8.8.4.4"
        - "4.2.2.4"
        - "1.1.1.1"
        - "5.202.100.101"
        - "5.202.100.100"
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
#        replacement: "time.ir"
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115  # The blackbox exporter's real hostname:port.

  ##______Blackbox HTTP________________##
  - job_name: 'blackbox-exporter-http'
    scrape_interval: 10s
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets: [https://aparat.com]
        labels:
          hostname: aparat
      - targets: [https://google.com]
        labels:
          hostname: google.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115  # The blackbox exporter's real hostname:port.
